### PR TITLE
feat: add logos

### LINKED ISSUE #6: Create a logo
Create a logo

### PR DESCRIPTION
**Pull request by eddycharly**
Add logos.

Please take a look and vote for your favourite one.

Fixes #6

### CODE REVIEW

**Comment by eddycharly** [comment]
My vote goes to logo-4 =)

**Comment by MariamFahmy98** [comment]
I think both 3 and 4 are good.

**Comment by swastik959** [comment]
logo 5 is also great and looks minimalist

**Comment by vishal-chdhry** [comment]
Logo 4 looks good

**Comment by anushkamittal2001** [comment]
My vote's for 4

**Comment by Sanskarzz** [comment]
My vote is also for 4 .

**Comment by realshuting** [comment]
Mine goes to 3👍

**Comment by eddycharly** [comment]
Number 4 is the winner :)

**Pull request merged**
