### PR TITLE
feat: added istio resources

### LINKED ISSUE #25: Use istio resources in istio demo
Use istio resources in istio demo:
- istio service, routes, gateway, etc...

### PR DESCRIPTION
**Pull request by swastik959**
added istio resources

### CODE REVIEW

**Comment by eddycharly** [comment]
@swastik959 fix CI please

**Comment by swastik959** [comment]
added istio resources
> 
> fixes #25

**Comment by swastik959** [comment]
@eddycharly please review it now

**Comment by eddycharly** [comment]
@swastik959 now there's a conflict 🤣

**Pull request closed without merging**
